#!/bin/bash
# Begin LSF Directives
#BSUB -P GEO130
#BSUB -N
#BSUB -W 0:30
#BSUB -nnodes  2
#BSUB -J RunHMR4
#BSUB -o RunHMR4_2.out
#BSUB -e RunHMR4_2.err
module load netlib-lapack/3.8.0
module load cuda
module unload darshan-runtime
module load gcc
module load hdf5
date
jsrun -n 12 -g1 -c6 -a1 --smpiargs="-gpu" nvprof --profile-from-start off -f -o Prof2_%q\{OMPI_COMM_WORLD_RANK\} ./sw4 hmr4.in.summit
