#!/bin/bash
#export HIP_VISIBLE_DEVICES=${SLURM_LOCALID}
export ROCR_VISIBLE_DEVICES=${SLURM_LOCALID}
rocprof  --trace-start off --sys-trace --hsa-trace --hip-trace -o RocInt2_${SLURM_PROCID}.csv $1 $2
